name: red_bull_flutter_case_study
description: "A new Flutter project."
publish_to: 'none'
version: 0.4.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.1
  http: ^1.2.0
  intl: ^0.18.1
  provider: ^6.1.1
  video_player: ^2.8.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: RbIcons
      fonts:
        - asset: assets/fonts/icons.ttf
