name: red_bull_flutter_case_study
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.1+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  go_router: ^13.0.1
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  assets:
    - assets/images/
