/// Flutter icons SporIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SporIcons
///      fonts:
///       - asset: fonts/SporIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class RbIcons {
  RbIcons._();

  static const _kFontFam = 'RbIcons';

  static const IconData mail = IconData(0xe900, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe901, fontFamily: _kFontFam);
  static const IconData folder = IconData(0xe902, fontFamily: _kFontFam);
  static const IconData photo = IconData(0xe903, fontFamily: _kFontFam);
  static const IconData video = IconData(0xe904, fontFamily: _kFontFam);
  static const IconData fourK = IconData(0xe905, fontFamily: _kFontFam);
  static const IconData fhd = IconData(0xe906, fontFamily: _kFontFam);
  static const IconData playFilled = IconData(0xe907, fontFamily: _kFontFam);
  static const IconData playOutlined = IconData(0xe908, fontFamily: _kFontFam);
}
